import Link from 'next/link';
export default function computational() {
    return(
        <div className="mt-4" style={{maxWidth: "50rem", margin: "3rem auto 6rem", paddingLeft:"20px",paddingRight:"20px"}}>
            <h1><b>Computational Astronomy</b></h1>
            <p>Computational Astronomy is a merger of Astronomy and Computer Science. Here, we use advanced computational techniques 
                and technologies to analyze, simulate, and model complex datasets generated by astronomical observations. 
                The key areas of computational astronomy includes data analysis, image processing, simulations and modelling, 
                gravitational wave astronomy, and exoplanet studies.
            </p>
            <p>The following github repository has some tutorials on the very basics of computational astronomy and we will be doing that 
                with the help of our best friend Python which has many libraries such as AstroPy and NumPy that make our lives much easier.
            </p>
            <h2><Link href="https://github.com/krittikaiitb/tutorials">Tutorials</Link></h2>
        </div>
    )
}